### ISSUE TITLE
Success rates are same for each template

### ISSUE THREAD

**Issue by ArchangelSDY** [jenkinsci/cloud-stats-plugin#10]
Hi,

We got following screenshot from our customer. They are reporting that success rates are same for all templates. I checked the code [here](https://github.com/jenkinsci/cloud-stats-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/cloudstats/CloudStatistics/index.groovy#L78) and there seems to be some typos: `ch` -> `th`. Could you have a look at that?

Thanks!

![cloud-stats](https://user-images.githubusercontent.com/858914/36522441-816160b6-17d7-11e8-8fa2-544b1482846c.jpg)

**Comment by medianick** [comment]
I'm the customer named above, and can confirm that I'm still seeing this. The three metrics listed above appear to be repeated for every template rather than being tracked/calculated for each one individually.

**Comment by medianick** [comment]
It looks like https://github.com/jenkinsci/cloud-stats-plugin/commit/a28517c351ab877cb4167c06d5f848ea87bef29f was meant to fix this issue, although even after installing Cloud Statistics 0.18, I still see the same Overall Success Rate and Current Success Rate values repeated for all templates.

![image](https://user-images.githubusercontent.com/329902/37522680-07bbfd9a-28fb-11e8-8fe2-a89b65c9d946.png)

Is this something that will only resolve itself with newly tracked statistics after 0.18 is installed? Shall I wipe out the existing statistics and start over?

**Comment by olivergondza** [comment]
The fix in https://github.com/jenkinsci/cloud-stats-plugin/commit/a28517c351ab877cb4167c06d5f848ea87bef29f was incomplete as it addresses sample count but not the success rates. Fixed in a483a5d.

**Comment by olivergondza** [comment]
Released as 0.19, it should be in update center soon.

**Comment by medianick** [comment]
Confirmed as fixed in 0.19. Thank you!

![image](https://user-images.githubusercontent.com/329902/46015864-5863c000-c0a1-11e8-8e39-974fea5ce65e.png)
