### ISSUE TITLE
ARCHIVE_RECORDS system property is ignored after initialization

### ISSUE THREAD

**Issue by yayachiken** [jenkinsci/cloud-stats-plugin#13]
The size of the cloud statistics "back log" seems to be configurable by setting the `org.jenkinsci.plugins.cloudstats.CloudStatistics.ARCHIVE_RECORDS` system property, with a default of 100 if it does not exist.

Once the XML file storing the state has been initialized though, any changes in the ARCHIVE_RECORDS system property seem to be ignored. I guess the size of the history array is saved in the XML as a fixed property and ARCHIVE_RECORDS is not used when the state is restored from the XML file.

In the code it seems as if there is already some migration code for the XML file. Would it be possible to grow or shrink the history array whenever the ARCHIVE_RECORDS property changed over Jenkins restarts?

A functional workaround is to stop jenkins, delete the cloud statistics XML file, and then restart jenkins with ARCHIVE_RECORDS system property set. Unfortunately, this loses all history.

In addition, setting the size of the backlog is a pretty neat feature and I was glad I found it when skimming the code. I think it might help others if it was documented in the README, the plugin page and/or even the Jenkins wiki page of configurable system properties.

Thanks!

(I hope the information is sufficient, as I encountered the problem during work and do not have access to a working Jenkins instance at home, so I cannot provide the actual file paths etc.)

**Comment by olivergondza** [comment]
Thanks, you are right. This is implemented i na way it only works initially.
