### ISSUE TITLE
Sanity check of the configuration entries

### ISSUE THREAD

**Issue by yatli** [jenkinsci/cloud-stats-plugin#5]
Hi!

I'm experiencing "oops" when I flip open the cloud stats side panel. The exception stack trace is about a null reference:

```
Caused by: java.lang.NullPointerException
	at org.jenkinsci.plugins.cloudstats.CyclicThreadSafeCollection.size(CyclicThreadSafeCollection.java:111)
	at org.jenkinsci.plugins.cloudstats.CloudStatistics.getActivities(CloudStatistics.java:146)
	at org.jenkinsci.plugins.cloudstats.CloudStatistics.getIndex(CloudStatistics.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

Here: 

```
ArrayList<ProvisioningActivity> out = new ArrayList<>(active.size() + log.size());
```

The only way to get a null pointer here is to new T[0] I guess?
So this means the config entry says 0.
Deleting the config file can solve the problem.

https://github.com/jenkinsci/cloud-stats-plugin/blob/caf0cda72fc9f974351475c08dd7705b908d9cf8/src/main/java/org/jenkinsci/plugins/cloudstats/CloudStatistics.java#L75

**Comment by olivergondza** [comment]
@yatli, sorry I missed this originally. Can you post the original `$JENKINS_HOME/org.jenkinsci.plugins.cloudstats.CloudStatistics.xml` so we can investigate and fix this?

Note, the field that is null is `CyclicThreadSafeCollection#data` so the NPE is comming from inside the `size()` method. Also, `new` operator will never return null regardless of constructor arguments.

Same problem: https://issues.jenkins-ci.org/browse/JENKINS-44929

**Comment by yatli** [comment]
Yep that's the same issue. Actually this bug can be easily reproduced. This is how I can trigger it:

1. docker run jenkins, setup an instance
2. install Azure VM agent plugin, which depends on the cloud stats.
3. Let it deploy a few VMs to populate cloud stats
4. docker stop the jenkins instance (I guess anything that kills the process will also trigger it)
5. docker start jenkins instance again
6. flip open the cloud stats side pane, and an exception is rendered.

**Comment by olivergondza** [comment]
Thanks, I will give it a try. So this should manifest after every restart when *Azure VM agent plugin* activities are tracked, right?

**Comment by yatli** [comment]
yes, every "unprepared" restart.

**Comment by olivergondza** [comment]
I am introducing [diagnosing](https://github.com/jenkinsci/cloud-stats-plugin/commit/c1c531e14e22b2d9f8733f7ba936356a72940dd7) to capture real broken XMLs. I did not get to creating azure account and the XMLs provided at https://issues.jenkins-ci.org/browse/JENKINS-44929 works fine for me...

**Comment by olivergondza** [comment]
Hey, any new samples of the problem?

**Comment by olivergondza** [comment]
Please reopen if you feel this is still an issue
