### ISSUE TITLE
Oops after upgrading to Jenkins 2.375.1: `Could not load class: org.jenkins.ui.icon.IconSet`

### ISSUE THREAD

**Issue by amotl** [jenkinsci/cloud-stats-plugin#53]
Dear lovely project maintainers,

first things first, I wish you a happy new year.

On upgrading our instance to Jenkins 2.375.1, we have been tripped by the issue outlined at [JENKINS-69966].

[JENKINS-69966]: https://issues.jenkins.io/browse/JENKINS-69966

### Observation
Jenkins displays an Ooops page, and, while being started, does not work at all.

![image](https://user-images.githubusercontent.com/453543/211624240-82042c1a-a835-4110-9c29-44a905581977.png)

### Problem
> Could not load class: org.jenkins.ui.icon.IconSet.
> Reason: java.lang.NoSuchMethodException: org.jenkins.ui.icon.IconSet.getSymbol()

```java
org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_cache/war/WEB-INF/lib/jenkins-core-2.375.jar!/hudson/model/View/sidepanel.jelly:75:50: <st:include> org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_cache/war/WEB-INF/lib/jenkins-core-2.375.jar!/lib/layout/pane.jelly:81:29: <d:invokeBody> org.apache.commons.jelly.JellyTagException: jar:file:/var/jenkins_cache/war/WEB-INF/lib/jenkins-core-2.375.jar!/lib/layout/icon.jelly:70:93: <j:invokeStatic> Could not load class: org.jenkins.ui.icon.IconSet. Reason: java.lang.NoSuchMethodException: org.jenkins.ui.icon.IconSet.getSymbol(java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
	at org.apache.commons.jelly.impl.TagScript.handleException(TagScript.java:719)
	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:277)
```

### Description
At [JENKINS-69966], they say:
> Occurs when cloud stats plugin is installed and at least one agent is tracked by cloud stats.
> Most likely caused by https://github.com/jenkinsci/jenkins/pull/7208.

Is there anything you could do about it?

With kind regards,
Andreas.

**Comment by MarkEWaite** [comment]
Have you installed the most recent release of the cloud stats plugin?

254.v47891b_b_5b_6f6 is the release that fixed that issue.  There has also been release [267.v577e3742c282](https://github.com/jenkinsci/cloud-stats-plugin/releases/tag/267.v577e3742c282) that includes other changes.

In general, when updating to a new long term support release, it is important to also update to the most recent releases of plugins.

**Comment by amotl** [comment]
Dear Mark,

thank you for the quick and swift response. I admit we did not update the cloud stats plugin _before_ upgrading to a new long term support release, and we will adjust our upgrade procedure accordingly in the future, as you suggested. Also, apologies for missing GH-30. I think we can consider this as being resolved. Sorry for the noise, and thank you so much.

With kind regards,
Andreas.
