### ISSUE TITLE
Feature: Hidden Cloud Statistics on main page

### ISSUE THREAD

**Issue by bartleboeuf** [jenkinsci/cloud-stats-plugin#7]
Hello, 

Can you add a "Hidden" feature of the "Cloud Statistics" box on main jenkins page ?

**Comment by olivergondza** [comment]
This is hidden when user do not have necessary permissions: https://github.com/jenkinsci/cloud-stats-plugin/commit/7161d8cf9ac9178d6dff7a1b56d53fc8557aab3f

Does it cover your use-case?

**Comment by bartleboeuf** [comment]
Yes it is ! (https://issues.jenkins-ci.org/browse/JENKINS-46100)
