### ISSUE TITLE
Modernize table appearance

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/cloud-stats-plugin#82]
### What feature do you want to see added?

The plugin uses the legacy `bigtable` design in https://github.com/jenkinsci/cloud-stats-plugin/blob/a4f9085f3daf2f673743e836512a72bee28f6bd0/src/main/resources/org/jenkinsci/plugins/cloudstats/CloudStatistics/index.groovy#L47 still.

To comply with the overall table design used in modern Jenkins, the plugin could make use of `jenkins-table`s, as documented in https://weekly.ci.jenkins.io/design-library/Table/

**Comment by ReCodee** [comment]
Hi @NotMyFault ,
This ticket looks good to me for getting started as a contributor.
Can I take this up?

**Comment by NotMyFault** [comment]
For sure!
